str = ''
str += '<nav class="lnb">'
str += '	<ul>'
str += '		<li class="depth01 menu01">'
str += '			<a href="javascript:" class="d1 on">관리자 계정 관리</a>'
str += '			<ul class="depth02">'
str += '				<li><a href="A.html">관리자 계정 관리</a></li>'
str += '			</ul>'
str += '		</li>'
str += '		<li class="depth01 menu02">'
str += '			<a href="javascript:" class="d1">메인 관리</a>'
str += '			<ul class="depth02">'
str += '				<li><a href="Z.html">메인 배너</a></li>'
str += '			</ul>'
str += '		</li>'
str += '		<li class="depth01 menu03">'
str += '			<a href="javascript:" class="d1">엑스포 관리</a>'
str += '			<ul class="depth02">'
str += '				<li><a href="B.html">엑스포 관리</a></li>'
str += '				<li><a href="C.html">신청기업 관리</a></li>'
str += '			</ul>'
str += '		</li>'
str += '		<li class="depth01 menu04">'
str += '			<a href="mainBannerList.html" class="d1">게시판 관리</a>'
str += '			<ul class="depth02">'
str += '				<li><a href="D.html">갤러리 게시판 관리</a></li>'
str += '				<li><a href="E.html">소셜뉴스 관리</a></li>'
str += '				<li><a href="F.html">소통방 관리</a></li>'
str += '				<li><a href="G.html">Q&A 관리</a></li>'
str += '			</ul>'
str += '		</li>'
str += '		<li class="depth01 menu05">'
str += '			<a href="javascript:" class="d1">소셜벤처 관리</a>'
str += '			<ul class="depth02">'
str += '				<li><a href="H.html">소셜벤처 기업 관리</a></li>'
str += '				<li><a href="I.html">수요목록 관리</a></li>'
str += '			</ul>'
str += '		</li>'
str += '		<li class="depth01 menu06">'
str += '			<a href="javascript:" class="d1">원스톱 창업 서비스 관리</a>'
str += '			<ul class="depth02">'
str += '				<li><a href="K.html">예약 관리</a></li>'
str += '				<li><a href="L.html">온라인 상담 관리</a></li>'
str += '			</ul>'
str += '		</li>'
str += '		<li class="depth01 menu07">'
str += '			<a href="javascript:" class="d1">소셜벤처 허브센터 관리</a>'
str += '			<ul class="depth02">'
str += '				<li><a href="M.html">회의실 관리</a></li>'
str += '				<li><a href="N.html">예약 관리</a></li>'
str += '			</ul>'
str += '		</li>'
str += '		<li class="depth01 menu08">'
str += '			<a href="javascript:" class="d1">메뉴 관리</a>'
str += '			<ul class="depth02">'
str += '				<li><a href="O.html">메뉴 관리</a></li>'
str += '			</ul>'
str += '		</li>'
// str += '		<li class="depth01 menu09">'
// str += '			<a href="javascript:" class="d1">통계</a>'
// str += '		</li>'
str += '	</ul>'
str += '</nav>'
str += '<hr />'

document.write(str);